name: Build Windows App

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행

jobs:
  build-windows:
    name: Windows Build
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'

      - name: Enable Windows Support
        run: flutter config --enable-windows-desktop

      - name: Create .env file
        run: echo "$ENV_FILE" > .env
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/x64/runner/Release/

      - name: List Windows Build Directory
        run: dir build/windows/x64/runner/Release/