name: Build Windows App

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행

jobs:
  build-windows:
    name: Windows Build
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'  # 원하는 Flutter 버전

      - name: Enable Windows Support
        run: flutter config --enable-windows-desktop

      - name: Create .env.production file
        run: |
          echo "API_URL=${{ secrets.API_URL }}" > assets/.env
          echo "CAFE_URL=${{ secrets.CAFE_URL }}" >> assets/.env
          echo "CHANNEL_ID_LIST=${{ secrets.CHANNEL_ID_LIST }}" >> assets/.env
          echo "SUB_CHANNEL_ID_LIST=${{ secrets.SUB_CHANNEL_ID_LIST }}" >> assets/.env
          echo "PACKAGE_NAME=${{ secrets.PACKAGE_NAME }}" >> assets/.env

      - name: Debug .env file
        run: cat assets/.env

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/x64/runner/Release/

      - name: List Windows Build Directory
        run: dir build/windows/x64/runner/Release/