name: Deploy Flutter Web to AWS S3

on:
  release:
    types: [published]  # 새로운 릴리즈가 생성될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "API_URL=${{ secrets.API_URL }}" > assets/.env
          echo "CAFE_URL=${{ secrets.CAFE_URL }}" >> assets/.env
          echo "CHANNEL_ID_LIST=${{ secrets.CHANNEL_ID_LIST }}" >> assets/.env
          echo "SUB_CHANNEL_ID_LIST=${{ secrets.SUB_CHANNEL_ID_LIST }}" >> assets/.env
          echo "PACKAGE_NAME=${{ secrets.PACKAGE_NAME }}" >> assets/.env
          echo "TEST_API_URL=${{ secrets.TEST_API_URL }}" >> assets/.env

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.4

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --web-renderer html --release

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy to S3
        run: aws s3 sync build/web s3://mystockprojectbucket --delete

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"